import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';


import Window from '../components/Window';
import Input from '../components/Input';

export type Todo = Readonly<{
  id: string;
  date: Date;
  task: string;
  done: boolean;
}>;

const Home: NextPage = () => {
  const [tasks, setTasks] = useState<Todo[]>([]);

  const addTask = (newTodo: Todo): void => {
    setTasks([...tasks, newTodo]);
  };

  return (
    <div className='max-w-2xl mx-auto my-10'>
      <Head>
        <title>Task Manager</title>
        <meta name='description' content='Generated by create next app' />
        {/* <link rel='icon' href='/favicon.ico' />
        <link rel='manifest' href='/site.webmanifest'></link> */}
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/apple-touch-icon.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon-32x32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/favicon-16x16.png'
        />
        <link rel='manifest' href='/site.webmanifest' />
        <link rel='mask-icon' href='/safari-pinned-tab.svg' color='#5bbad5' />
        <meta name='msapplication-TileColor' content='#2b5797' />
        <meta name='theme-color' content='#ffffff'></meta>
      </Head>
      <Input addTask={addTask} />
      {tasks.map((task) => (
        <Window key={task.id} {...task} />
      ))}
    </div>
  );
};

export default Home;
